name: Build with conda
on:
  push:
  pull_request:

jobs:
  unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [clang, gcc]

        include:
          - compiler: clang
            CC: clang
            CXX: clang++
          - compiler: gcc
            CC: gcc
            CXX: g++
            
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main

        with:
          environment-file: environment_unix.yml
          environment-name: arcticdb

      - name: Install dedicated compiler
        shell: bash -l {0}
        run: |
          micromamba install ${{ matrix.compiler }}
 
      - name: Build
        shell: bash -l {0}
        run: |
          python -m pip install -v -e .
        env:
          ARCTICDB_USING_CONDA: 1
          CC: "$CONDA_PREFIX/bin/{{matrix.CC}}"
          CXX: "$CONDA_PREFIX/bin/{{matrix.CXX}}"

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          cd python
          python -m pytest tests